export const VALIDATE_USER_WITH_EMAIL_EVENT = 'VALIDATE_USER_WITH_EMAIL_EVENT';
export const VALIDATE_USER_WITH_USERNAME_EVENT = 'VALIDATE_USER_WITH_USERNAME_EVENT';
export const SIGNUP_USER_WITH_EMAIL_EVENT = 'SIGNUP_USER_WITH_EMAIL_EVENT';
export const REFRESH_TOKEN_EVENT = 'REFRESH_TOKEN_EVENT';
