export const EDRADOP_DEFAULT_PORT = 3023;
export const ANALYTIC_DEFAULT_PORT = 3001;
export const AUTHENTICATION_DEFAULT_PORT = 3002;
export const PAYMENT_DEFAULT_PORT = 3003;
export const STORAGE_DEFAULT_PORT = 3004;
export const USER_DEFAULT_PORT = 3045;
