export const EDRADOP_DEFAULT_PORT = 3000;
export const ANALYTIC_DEFAULT_PORT = 3001;
export const AUTHENTICATION_DEFAULT_PORT = 3002;
export const COMMUNICATION_DEFAULT_PORT = 3003;
export const PAYMENT_DEFAULT_PORT = 3004;
export const STORAGE_DEFAULT_PORT = 3005;
export const USER_DEFAULT_PORT = 3006;
